spring:
  application:
    name: Yagoo
  jpa:
    hibernate:
      #ddl 설정
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

# mysql 연결
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/heemin?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 1234

# 서버 포트 설정
server:
  port: 8081





